import { Product } from '../types';

export const INITIAL_PRODUCTS: Omit<Product, 'createdAt' | 'updatedAt'>[] = [
  // CATS
  {
    id: 'cat-interactive-laser-toy',
    title: 'Interactive Cat Toy & Motion Teaser',
    slug: 'interactive-cat-toy',
    category: 'Cats',
    shortDescription: 'Autonomous 360-degree rotating laser and feather teaser to stimulate hunting instincts.',
    description: 'Keep indoor cats energized and mentally stimulated throughout the day. Features dual interactive modes including an erratic spinning feather wand and safe optical patterns with automatic shut-off intervals after 15 minutes of continuous exercise.',
    imageUrl: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1545249390-6bdfa286032f?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=interactive+cat+toy&tag=pawmart0e-20',
    viewsCount: '1.6k',
    reviews: [
      {
        id: 'rev-1',
        author: 'Jessica M.',
        rating: 5,
        title: 'My cats are obsessed with this toy!',
        comment: 'Both my indoor cats usually get bored with toys in 5 minutes, but this automatic laser and feather combo kept them running and pouncing happily. The automatic shut-off feature is a lifesaver.',
        date: 'Sep 18, 2026',
        verifiedPurchase: true,
      },
      {
        id: 'rev-2',
        author: 'David K.',
        rating: 5,
        title: 'Sturdy, quiet motor and high battery life',
        comment: 'Great build quality and very quiet motor compared to other spinners. Gives my energetic tabby plenty of exercise while I work from home.',
        date: 'Sep 22, 2026',
        verifiedPurchase: true,
      },
    ],
    featured: true,
    published: true,
  },
  {
    id: 'cat-scratching-board-lounge',
    title: 'Ergonomic Cat Scratching Board & Lounge',
    slug: 'cat-scratching-board',
    category: 'Cats',
    shortDescription: 'High-density corrugated cardboard reversible scratch pad designed for resting and claws.',
    description: 'Crafted from 100% recycled heavy-duty honeycomb cardboard, this sleek curved scratcher protects your household furniture while providing a contoured, comfortable nesting cradle for long naps.',
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=cat+scratching+board&tag=pawmart0e-20',
    viewsCount: '2.4k',
    featured: false,
    published: true,
  },
  {
    id: 'cat-automatic-timed-feeder',
    title: 'Automatic Cat Feeder with Voice Call',
    slug: 'automatic-cat-feeder',
    category: 'Cats',
    shortDescription: 'Programmable dry food dispenser with desiccant sealed bag and voice recording reminder.',
    description: 'Ensure consistent portion control whether you are at work or out for the weekend. Features up to 6 scheduled meals per day, anti-clog dispensing architecture, and battery backup support for uninterrupted power during outages.',
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=automatic+cat+feeder&tag=pawmart0e-20',
    viewsCount: '3.8k',
    featured: true,
    published: true,
  },
  {
    id: 'cat-grooming-slicker-brush',
    title: 'Self-Cleaning Cat Grooming Brush',
    slug: 'cat-grooming-brush',
    category: 'Cats',
    shortDescription: 'One-click hair release deshedding tool with massage tips suitable for all coat lengths.',
    description: 'Gently removes loose undercoat, dander, and trapped dirt without scratching sensitive skin. The stainless steel curved wire pins retract with a single button click, letting you wipe away collected fur in one quick motion.',
    imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=cat+grooming+brush&tag=pawmart0e-20',
    viewsCount: '1.9k',
    featured: false,
    published: true,
  },

  // DOGS
  {
    id: 'dog-durable-rubber-chew-toy',
    title: 'Durable Dog Toy for Aggressive Chewers',
    slug: 'durable-dog-toy',
    category: 'Dogs',
    shortDescription: 'Natural non-toxic puncture-resistant rubber toy with textured treat-dispensing grooves.',
    description: 'Engineered specifically for medium to large power chewers. Tested rigorously against tough biters, this textured bouncing rubber toy promotes dental hygiene by scraping plaque while rewarding dogs during solo play sessions.',
    imageUrl: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=durable+dog+chew+toy&tag=pawmart0e-20',
    viewsCount: '4.2k',
    featured: true,
    published: true,
  },
  {
    id: 'dog-portable-water-bottle-travel',
    title: 'Portable Dog Water Bottle & Feeder',
    slug: 'portable-dog-water-bottle',
    category: 'Dogs',
    shortDescription: 'One-hand leakproof travel dispenser with leaf-style silicone drinking bowl.',
    description: 'Keep your companion hydrated on hikes, park runs, and road trips. Simply push the lock button to release clean water into the ergonomic trough, then tilt back to reclaim unused water with zero waste.',
    imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=portable+dog+water+bottle&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'dog-walking-no-pull-accessories',
    title: 'Reflective Dog Walking Harness & Leash Set',
    slug: 'dog-walking-accessories',
    category: 'Dogs',
    shortDescription: 'Breathable padded no-pull harness with 3M reflective safety stitching and traffic handle.',
    description: 'Distributes pulling pressure evenly across chest and shoulders to prevent neck strain. Features dual lead attachment rings for training control, sturdy quick-release side buckles, and bright luminous piping for nighttime visibility.',
    imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=dog+walking+accessories+harness&tag=pawmart0e-20',
    featured: false,
    published: true,
  },
  {
    id: 'dog-grooming-undercoat-brush',
    title: 'Dual-Sided Dog Grooming Undercoat Rake',
    slug: 'dog-grooming-brush',
    category: 'Dogs',
    shortDescription: 'Dematting and thinning rake with rounded exterior teeth that glide effortlessly through dense coats.',
    description: 'Drastically cuts down shedding by up to 95%. Features a 9-tooth side for stubborn mats and tangles, paired with a 17-tooth side for deep undercoat thinning. Safe rounded blades ensure no nicks or skin agitation.',
    imageUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=dog+grooming+undercoat+rake&tag=pawmart0e-20',
    featured: false,
    published: true,
  },

  // T-SHIRTS
  {
    id: 'tshirt-minimal-paw-graphic',
    title: 'Minimal Graphic T-Shirt',
    slug: 'minimal-graphic-t-shirt',
    category: 'T-Shirts',
    shortDescription: 'Subtle clean line-art print on 100% ring-spun combed organic cotton.',
    description: 'A timeless minimalist wardrobe piece designed for animal enthusiasts. Tailored with a pre-shrunk unisex regular fit, ribbed crew neckline, and breathable lightweight combed cotton suitable for year-round layering.',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=minimalist+graphic+t+shirt&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'tshirt-classic-heavyweight-cotton',
    title: 'Classic Heavyweight Cotton T-Shirt',
    slug: 'classic-cotton-t-shirt',
    category: 'T-Shirts',
    shortDescription: 'Sturdy 6.5 oz combed jersey tee with reinforced collar and relaxed vintage drape.',
    description: 'Built for durability and clean everyday style. Constructed from dense ringspun cotton that softens with every wash while retaining its structured boxy silhouette, double-needle hemmed sleeves, and non-itch interior tag.',
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=classic+cotton+t+shirt&tag=pawmart0e-20',
    featured: false,
    published: true,
  },
  {
    id: 'tshirt-casual-everyday-crew',
    title: 'Casual Everyday T-Shirt',
    slug: 'casual-everyday-t-shirt',
    category: 'T-Shirts',
    shortDescription: 'Super-soft tri-blend crew neck with moisture-wicking properties and modern fit.',
    description: 'The definitive all-day t-shirt for weekend dog park walks, errand runs, or casual meetups. Blend of cotton, modal, and elastane delivers four-way stretch, subtle drape, and exceptional longevity.',
    imageUrl: 'https://images.unsplash.com/photo-1527719327859-c6ce80353573?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=casual+everyday+crew+tshirt&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'tshirt-unisex-retro-graphic',
    title: 'Unisex Retro Graphic T-Shirt',
    slug: 'unisex-graphic-t-shirt',
    category: 'T-Shirts',
    shortDescription: 'Distressed vintage-inspired pet companion illustration with soft water-based inks.',
    description: 'Inspired by 1980s national park posters and outdoor aesthetics. Screen printed with environmentally conscious water-based inks that do not crack or feel heavy on the fabric, paired with an athletic relaxed cut.',
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=unisex+graphic+t+shirt&tag=pawmart0e-20',
    featured: false,
    published: true,
  },

  // HOODIES
  {
    id: 'hoodie-classic-fleece-pullover',
    title: 'Classic Pullover Hoodie',
    slug: 'classic-pullover-hoodie',
    category: 'Hoodies',
    shortDescription: 'Heavyweight 400 GSM brushed interior fleece hoodie with double-layer hood.',
    description: 'Wrap yourself in premium warmth. Built with high-gauge cotton face yarn, sturdy ribbed cuffs, metal-tipped woven flat drawstrings, and a kangaroo pouch pocket designed to keep hands warm in chilly weather.',
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=classic+pullover+hoodie&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'hoodie-minimal-streetwear-oversized',
    title: 'Minimal Streetwear Hoodie',
    slug: 'minimal-streetwear-hoodie',
    category: 'Hoodies',
    shortDescription: 'Dropped shoulder oversized boxy cut with clean tonal embroidery and cuff detailing.',
    description: 'A contemporary silhouette combining modern streetwear proportions with plush comfort. Features an unlined structured hood that maintains its shape without drawstrings, plus seamless side construction.',
    imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=minimalist+streetwear+hoodie&tag=pawmart0e-20',
    featured: false,
    published: true,
  },
  {
    id: 'hoodie-casual-unisex-comfort',
    title: 'Casual Unisex Hoodie',
    slug: 'casual-unisex-hoodie',
    category: 'Hoodies',
    shortDescription: 'Light-to-midweight French terry pullover crafted for versatile all-season wear.',
    description: 'Perfect for morning walks and cozy indoor lounging. Crafted from breathable cotton French terry loops with flatlock reinforced seam construction and ribbed side gussets for unhindered mobility.',
    imageUrl: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=casual+unisex+hoodie&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'hoodie-everyday-thermal-fleece',
    title: 'Everyday Fleece Hoodie',
    slug: 'everyday-fleece-hoodie',
    category: 'Hoodies',
    shortDescription: 'Super-soft pill-resistant fleece with weather-resistant outer blend and roomy hood.',
    description: 'Engineered for outdoor durability and easy machine-wash care. Features anti-pill treated yarn, high storm collar under the hood, and durable bar-tacked stress points on pocket openings.',
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=everyday+fleece+hoodie&tag=pawmart0e-20',
    featured: false,
    published: true,
  },

  // BOOKS
  {
    id: 'book-beginner-pet-care-guide',
    title: 'Beginner Pet Care Guide: Health & Nutrition',
    slug: 'beginner-pet-care-guide',
    category: 'Books',
    shortDescription: 'A friendly step-by-step master handbook for first-time dog and cat parents.',
    description: 'Written by certified veterinary consultants, this practical guide walks new pet owners through home-proofing, age-appropriate nutrition protocols, early vaccination schedules, and stress-free socialization techniques.',
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=beginner+pet+care+guide&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'book-dog-training-positive-reinforcement',
    title: 'The Modern Dog Training Guide',
    slug: 'dog-training-guide',
    category: 'Books',
    shortDescription: 'Evidence-based positive reinforcement tactics for leash manners, recall, and calm behavior.',
    description: 'Eliminate unwanted behaviors through science-backed compassionate communication. Includes illustrated daily training routines, crate transition blueprints, and reactive dog desensitization guides.',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=dog+training+guide+positive+reinforcement&tag=pawmart0e-20',
    featured: true,
    published: true,
  },
  {
    id: 'book-cat-care-feline-handbook',
    title: 'Cat Care Handbook: Decoding Feline Language',
    slug: 'cat-care-handbook',
    category: 'Books',
    shortDescription: 'An insightful exploration of subtle body language, environmental enrichment, and health.',
    description: 'Understand what your cat is really thinking. Explores vocalization cues, tail positioning, indoor territory mapping, multi-cat household harmony, and preventative senior feline health markers.',
    imageUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777f?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=cat+care+handbook+behavior&tag=pawmart0e-20',
    featured: false,
    published: true,
  },
  {
    id: 'book-pet-lovers-illustrated-companion',
    title: "Pet Lover's Illustrated Guide & Anthology",
    slug: 'pet-lovers-guide',
    category: 'Books',
    shortDescription: 'Heartwarming true stories, historical lore, and full-color portraits celebrating pets.',
    description: 'A coffee-table masterpiece showcasing extraordinary human-animal bonds across continents and history. Packed with lush photography, inspiring rescue tales, and wisdom from legendary animal advocates.',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1000&auto=format&fit=crop',
    amazonAffiliateLink: 'https://www.amazon.com/s?k=pet+lovers+guide+stories&tag=pawmart0e-20',
    featured: false,
    published: true,
  },

  // FURNITURE
  {
    id: 'furniture-ergonomic-mesh-chair',
    title: 'Ergonomic High-Back Executive Mesh Chair',
    slug: 'ergonomic-high-back-mesh-chair',
    category: 'Furniture',
    shortDescription: 'Breathable mesh chair with 3D adjustable armrests, lumbar support, and smooth recline.',
    description: 'Engineered for all-day comfort whether working remotely or relaxing. Features responsive adaptive lumbar cushioning, heavy-duty alloy wheelbase, pneumatic height cylinder, and 135-degree recline lock.',
    imageUrl: 'https://images.unsplash.com/photo-1580481077195-c328a37db71a?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1580481077195-c328a37db71a?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1505797149-43b0069ec26b?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=ergonomic+mesh+office+chair&tag=pawmart0e-20',
    viewsCount: '3.8k',
    featured: true,
    published: true,
  },
  {
    id: 'furniture-minimalist-coffee-table',
    title: 'Modern Minimalist Coffee Table with Shelf',
    slug: 'minimalist-coffee-table-shelf',
    category: 'Furniture',
    shortDescription: 'Sturdy water-resistant wood grain table with powder-coated steel frame.',
    description: 'A stylish centerpiece for modern living rooms. Features an open lower storage tier for magazines, games, and baskets, rounded corner edges for pet and child safety, and adjustable non-scratch leveling feet.',
    imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=modern+minimalist+coffee+table&tag=pawmart0e-20',
    viewsCount: '1.9k',
    featured: false,
    published: true,
  },

  // SHOES
  {
    id: 'shoes-ultra-cushioned-running',
    title: 'Ultra-Cushioned Lightweight Running Sneakers',
    slug: 'ultra-cushioned-running-sneakers',
    category: 'Shoes',
    shortDescription: 'High-rebound EVA foam running shoes with breathable knit upper and anti-slip grip.',
    description: 'Designed for daily runs, active dog walks, and gym sessions. The engineered jacquard mesh delivers continuous airflow, while the shock-absorbing dual-density midsole protects joints on hard pavement.',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=lightweight+running+sneakers&tag=pawmart0e-20',
    viewsCount: '2.9k',
    featured: true,
    published: true,
  },
  {
    id: 'shoes-casual-slip-on-loafers',
    title: 'Comfort Casual Slip-On Walking Loafers',
    slug: 'casual-slip-on-walking-loafers',
    category: 'Shoes',
    shortDescription: 'Easy on/off memory foam loafers with flexible arch support and lightweight sole.',
    description: 'Step into effortless style for errands, travel, or casual weekend outings. Features moisture-wicking canvas, padded collar to prevent heel chafing, and flexible grooved outsoles that move naturally with your feet.',
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=casual+slip+on+shoes&tag=pawmart0e-20',
    viewsCount: '1.4k',
    featured: false,
    published: true,
  },

  // WEDDING COLLECTION
  {
    id: 'wedding-crystal-bridal-jewelry-set',
    title: 'Sparkling Crystal Bridal Necklace & Earrings Set',
    slug: 'crystal-bridal-jewelry-set',
    category: 'Wedding Collection',
    shortDescription: 'Hypoallergenic platinum-plated teardrop cubic zirconia jewelry for brides and bridesmaids.',
    description: 'Add timeless sparkle to your wedding day. Crafted with brilliant AAA-grade cubic zirconia crystals that catch ambient light from every angle. Nickel-free, lead-free, and packaged in an elegant velvet gift box.',
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=bridal+jewelry+set+wedding&tag=pawmart0e-20',
    viewsCount: '1.8k',
    featured: true,
    published: true,
  },
  {
    id: 'wedding-custom-guest-book-keepsake',
    title: 'Vintage Gold Foil Wedding Guest Book',
    slug: 'vintage-gold-foil-guest-book',
    category: 'Wedding Collection',
    shortDescription: 'Linen hardcover memorial guestbook with heavyweight archival bleed-proof pages.',
    description: 'Preserve cherished well-wishes and signatures for decades. Features embossed gold foil lettering on durable natural linen cloth, ribbon bookmark, and lay-flat Smyth-sewn binding for effortless signing.',
    imageUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=wedding+guest+book+hardcover&tag=pawmart0e-20',
    viewsCount: '980',
    featured: false,
    published: true,
  },

  // ELECTRONICS
  {
    id: 'electronics-wireless-anc-headphones',
    title: 'Hybrid Active Noise Cancelling Wireless Headphones',
    slug: 'anc-wireless-headphones',
    category: 'Electronics',
    shortDescription: 'Over-ear Hi-Res audio headphones with 40-hour battery life and transparency mode.',
    description: 'Block out ambient distractions and immerse yourself in pristine acoustic clarity. Custom 40mm dynamic drivers deliver punchy bass and crystalline trebles, while rapid USB-C charging delivers 4 hours of playtime in just 10 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=noise+cancelling+headphones+bluetooth&tag=pawmart0e-20',
    viewsCount: '5.2k',
    featured: true,
    published: true,
  },
  {
    id: 'electronics-smart-pet-hd-camera',
    title: 'Smart 1080p HD Pet Camera with Night Vision & 2-Way Audio',
    slug: 'smart-pet-camera-night-vision',
    category: 'Electronics',
    shortDescription: 'WiFi security camera with real-time motion alerts, pan-tilt rotation, and companion app.',
    description: 'Check in on your pets anytime, anywhere from your smartphone. Features 355-degree horizontal panoramic rotation, infrared crisp night vision, sound detection alerts, and clear 2-way microphone communication.',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=smart+pet+camera+wifi&tag=pawmart0e-20',
    viewsCount: '3.6k',
    featured: false,
    published: true,
  },

  // JEWELRY COLLECTION
  {
    id: 'jewelry-14k-gold-tennis-bracelet',
    title: '14K Gold Plated Sparkling Cubic Zirconia Tennis Bracelet',
    slug: '14k-gold-plated-tennis-bracelet',
    category: 'Jewelry Collection',
    shortDescription: 'Classic 4mm round-cut cubic zirconia tennis bracelet with double-latch safety clasp.',
    description: 'Elevate any ensemble with this timeless brilliant tennis bracelet. Crafted with premium 14K yellow gold plating over lead-free, nickel-free hypoallergenic brass, featuring round AAA+ cubic zirconia stones with bezel-grade setting.',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=tennis+bracelet+14k+gold+plated&tag=pawmart0e-20',
    viewsCount: '4.8k',
    reviews: [
      {
        id: 'rev-j1',
        author: 'Sarah L.',
        rating: 5,
        title: 'Looks like real diamonds! Stunning sparkle',
        comment: 'I wear this every single day, even in the shower, and the shine hasn’t dulled at all. Clasp is very secure and comfortable.',
        date: 'Sep 12, 2026',
        verifiedPurchase: true,
      }
    ],
    featured: true,
    published: true,
  },
  {
    id: 'jewelry-sterling-silver-pendant-necklace',
    title: '925 Sterling Silver Minimalist Solitaire Pendant Necklace',
    slug: 'sterling-silver-solitaire-necklace',
    category: 'Jewelry Collection',
    shortDescription: 'Delicate 18-inch cable chain with bezel-set brilliant crystal solitaire pendant.',
    description: 'Understated elegance designed for everyday luxury. Features solid 925 sterling silver with rhodium anti-tarnish protective coating, an adjustable lobster clasp chain, and sparkling diamond-alternative solitaire.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=sterling+silver+solitaire+pendant+necklace&tag=pawmart0e-20',
    viewsCount: '2.9k',
    featured: false,
    published: true,
  },

  // OTHER PRODUCTS
  {
    id: 'other-smart-reusable-digital-notebook',
    title: 'Smart Reusable Cloud Sync Wirebound Notebook',
    slug: 'smart-reusable-cloud-notebook',
    category: 'Other Products',
    shortDescription: 'Eco-friendly erasable dot grid notebook with pen and cloud scanner app integration.',
    description: 'Never buy another paper notepad again. Write naturally with any Pilot FriXion pen, beam your handwritten notes instantly to Google Drive, Dropbox, or email via the companion app, and wipe pages clean with a damp cloth for endless reuse.',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=smart+reusable+notebook&tag=pawmart0e-20',
    viewsCount: '3.9k',
    reviews: [
      {
        id: 'rev-other-1',
        author: 'Daniel M.',
        rating: 5,
        title: 'Incredible for daily productivity',
        comment: 'I use this for meetings every day. Scans crisp and clean, and erasing is so fast. Saves so much paper!',
        date: 'Oct 01, 2026',
        verifiedPurchase: true,
        adminReply: {
          author: 'PawMart Team',
          comment: 'Thank you for the wonderful feedback Daniel! It truly is one of our favorite productivity essentials.',
          date: 'Oct 02, 2026'
        }
      }
    ],
    featured: true,
    published: true,
  },
  {
    id: 'other-multipurpose-travel-cord-organizer',
    title: 'Water-Resistant Compact Electronics & Accessories Organizer',
    slug: 'compact-travel-cord-organizer',
    category: 'Other Products',
    shortDescription: 'Double-layer portable organizer pouch for cables, chargers, drives, and everyday essentials.',
    description: 'Keep your daily tech accessories tidy and tangle-free. Crafted with heavy-duty splash-resistant nylon and padded interior compartments, elastic loops for cords, and zippered mesh pockets for small essentials.',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=travel+cable+organizer+case&tag=pawmart0e-20',
    viewsCount: '2.1k',
    featured: false,
    published: true,
  },

  // KIDS TOYS
  {
    id: 'kids-toys-magnetic-building-blocks-set',
    title: '100-Piece 3D Magnetic Building Tiles STEM Toy Set',
    slug: 'magnetic-building-blocks-stem-set',
    category: 'Kids Toys',
    shortDescription: 'Colorful translucent magnetic building blocks that spark creativity, geometry skills, and hands-on STEM play.',
    description: 'Inspire hours of screen-free imaginative construction for children ages 3 and up. Built with ultrasonic-welded BPA-free ABS plastic and strong permanent magnets so kids can build towering castles, rockets, and geometric 3D structures safely.',
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=magnetic+building+tiles+kids+toys&tag=pawmart0e-20',
    viewsCount: '3.4k',
    featured: true,
    published: true,
  },
  {
    id: 'kids-toys-wooden-montessori-activity-cube',
    title: 'Montessori 6-in-1 Wooden Learning Activity Cube',
    slug: 'montessori-wooden-learning-activity-cube',
    category: 'Kids Toys',
    shortDescription: 'Interactive natural wood sensory puzzle cube with bead maze, shape sorter, and counting abacus.',
    description: 'Designed with smooth water-based non-toxic paint and rounded edges, this multi-activity learning center develops fine motor coordination, color recognition, and early problem-solving skills for toddlers and young learners.',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=wooden+montessori+activity+cube+kids+toy&tag=pawmart0e-20',
    viewsCount: '2.2k',
    featured: false,
    published: true,
  },

  // SKIN CARE
  {
    id: 'skin-care-vitamin-c-hyaluronic-serum',
    title: 'Brightening Vitamin C & Hyaluronic Acid Facial Serum',
    slug: 'vitamin-c-hyaluronic-acid-facial-serum',
    category: 'Skin Care',
    shortDescription: 'Antioxidant-rich daily glow serum with botanical vitamin E and pure hyaluronic hydration.',
    description: 'Revitalize dull, tired skin with a lightweight, fast-absorbing daily serum. Formulated with 20% L-Ascorbic Acid (Vitamin C), botanical hyaluronic acid, and soothing aloe vera to deeply hydrate, even out skin tone, and boost natural radiance.',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=vitamin+c+hyaluronic+acid+serum+skin+care&tag=pawmart0e-20',
    viewsCount: '4.1k',
    featured: true,
    published: true,
  },
  {
    id: 'skin-care-ceramide-hydrating-daily-cleanser',
    title: 'Gentle Ceramide & Niacinamide Hydrating Facial Cleanser',
    slug: 'ceramide-hydrating-daily-cleanser',
    category: 'Skin Care',
    shortDescription: 'Fragrance-free barrier-repair face wash for normal, dry, and sensitive skin types.',
    description: 'Cleanse away makeup, excess oil, and impurities without stripping your natural moisture barrier. Enriched with three essential ceramides, soothing niacinamide, and glycerin for soft, balanced skin morning and night.',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop'
    ],
    amazonAffiliateLink: 'https://www.amazon.com/s?k=hydrating+ceramide+facial+cleanser+skin+care&tag=pawmart0e-20',
    viewsCount: '2.9k',
    featured: false,
    published: true,
  }
];
